project:
  type: website

execute: 
  freeze: auto

format:
  html:
    toc: true

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website:
  title: "xraypy"
  navbar:
    background: light
    pinned: true
    search: true
    toc: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Reference"
        file: reference/index.qmd 
      - text: "Changelog"
        file: NEWS.md
    right:
      - text: "v.0.0.0.9000"
      - icon: github
        href: https://github.com/uskovgs/xraypy

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: xraypy

  # write sidebar data to this file
  sidebar: _sidebar.quartoyml

  sections:
    - title: High level functions
      desc: Functions for correct confidence intervals.
      package: xraypy.latex_table
      contents:
        - latex_range
        - latex_range_sci
    - title: Mid level functions
      desc: 
      package: xraypy.latex_table
      contents:
      - check_ndigits
      - get_first_digit
      - get_n_signif_digits
      - calc_signif_digits
      - format_number
      - round_vec
      